### ISSUE TITLE
ollama运行错误

### ISSUE THREAD

**Issue by gdtiti** [HIT-SCIR/Abacus#2]
ollama运行错误 不管问啥 返回的内容都是 
<h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/><h4/>
这样的乱码

**Comment by gdtiti** [comment]
< h 4 / >< h 4 / >< h 4 / >< h 4 / >< h 4 / >< h 4 / >< h 4 / > 这样的乱码

**Comment by noforit** [comment]
您好，可以看下截图吗，还有具体是怎么启动的模型。
经过测试，拉取ollama上的HIT-SCIR/abacus ，可以正常输出。命令如下：
```
ollama serve
ollama run HIT-SCIR/abacus
```
![image](https://github.com/user-attachments/assets/e07c6b92-153e-4cb5-9bb5-ccfb04a1fe55)
如果是本地导入模型，可以参考
https://github.com/HIT-SCIR/Abacus?tab=readme-ov-file#ollama%E9%83%A8%E7%BD%B2
本地导入模型时，若不配置chat_template 需要在问句前后加上`<用户><AI>`（拉取ollama仓库模型则不需要）
为了避免重复手动添加`<用户><AI>`字段，推荐在构建Modelfile时，添加template
```
{{ if .System }}{{ .System }}{{ end }}{{ if .Prompt }}<用户>{{ .Prompt }}{{ end }}<AI>{{ .Response }}
```
这样可以直接对话。
感激试用珠算模型，如果还有任何问题和不明白的地方，提出即可。

**Comment by gdtiti** [comment]
我删除本地模型重新拉取一次就没有报错了 可能是本地拷贝时文件损坏了
